import "./globals.css";

import { NavigationTopbar } from "@/components/navigation/topbar";
import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";

const displaySans = Roboto({
  weight: "400",
  variable: "--font-sans",
  subsets: ["latin"],
});

const displayMono = Roboto_Mono({
  weight: "400",
  variable: "--font-mono",
  subsets: ["latin"],
});
// const geistSans = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = DM_Sans({
//   variable: "--font-dm-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${displaySans.variable} ${displayMono.variable} antialiased bg-background`}
      >
        <div className="flex flex-col font-sans w-screen h-screen text-sm overflow-y-auto scroll-smoth">
          <NavigationTopbar />

          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
