import "./globals.css";

import type { Metadata } from "next";
import { Roboto, Roboto_Mono, Gabriela } from "next/font/google";
import { NavigationTopbar } from "@/components/navigation/topbar";

const displaySans = Roboto({
  weight: "400",
  variable: "--font-sans",
  subsets: ["latin"],
});

const displayMono = Roboto_Mono({
  weight: "400",
  variable: "--font-mono",
  subsets: ["latin"],
});
// const geistSans = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = DM_Sans({
//   variable: "--font-dm-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${displaySans.variable} ${displayMono.variable} antialiased`}
      >
        <div className="font-sans w-screen h-screen text-sm overflow-y-auto">
          <NavigationTopbar />
          <div className="w-full bg-center bg-background bg-no-repeat bg-cover bg-blend-color bg-opacity-50 h-full flex flex-col overflow-y-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
